apiVersion: v1
kind: Pod
metadata:
  name: normal-pod
spec:
  volumes:
    - name: rwx-dev
      emptyDir: {}
  containers:
    - name: normal-container
      image: nginx:1.24.0
      command: ["sh", "-c", "sleep 1h"]
      volumeMounts:
        - name: rwx-dev
          mountPath: /learn/kubernetes
