apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsUser: 1000
  volumes:
    - name: rwx-dev
      emptyDir: {}
  containers:
    - name: secure-container
      image: nginx:1.24.0
      command: ["sh", "-c", "sleep 1h"]
      volumeMounts:
        - name: rwx-dev
          mountPath: /learn/kubernetes
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyFileSystem: true
        capabilities:
          drop:
            - ALL